__include__: [
  '../dataset/coco_player.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

# Load pretrained weights
tuning: https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetrv2_r50vd_6x_coco_ema.pth

# Output directory
output_dir: ./output/rtdetrv2_r50vd_player_60epoches

epoches: 60

# Lower learning rate for fine-tuning
optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00005
    - 
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00005
      weight_decay: 0.
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.
  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 10
  collate_fn:
    stop_epoch: 10